# Site
domain: carlospsjr.github.io      # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
name: "Organização, Planejamento, Saúde"
title: "Organização, Planejamento, Saúde"
description: "Organização, Planejamento, Saúde"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /ops/ # the subpath of your site, e.g. /blog
url: https://carlospsjr.github.io/ops/ # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: ''
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  john:
    name: John
    display_name: John    
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
